version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false
  mapasnet:
    external: false

services:
    traefik:
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '$PWD/traefik.toml:/traefik.toml'
            - '$PWD/traefik_dynamic.toml:/traefik_dynamic.toml'
            - '$PWD/acme.json:/acme.json'
        ports:
            - '80:80'
            - '443:443'
        network_mode: web
        container_name: traefik
        image: 'traefik:v2.2'

    blog:
        image: wordpress:4.9.8-apache
        environment:
             WORDPRESS_DB_PASSWORD: miplataenobras
        labels:
            - traefik.http.routers.blog.rule=Host(`proandtech.com`)
            - traefik.http.routers.blog.tls=true
            - traefik.http.routers.blog.tls.certresolver=lets-encrypt
            - traefik.port=80
        networks:
            - internal
            - web
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        environment:
             MYSQL_ROOT_PASSWORD: miplataenobras
        networks:
            - internal
        labels:
            - traefik.enable=false

    mapa:
        image: wordpress:4.9.8-apache
        environment:
             WORDPRESS_DB_PASSWORD: elmapadeobras
             WORDPRESS_DB_HOST: mysql2
        labels:
            - traefik.http.routers.mapa.rule=Host(`mapa.proandtech.com`)
            - traefik.http.routers.mapa.tls=true
            - traefik.http.routers.mapa.tls.certresolver=lets-encrypt
            - traefik.port=80
        networks:
            - mapasnet
            - web
        depends_on:
            - mysql2

    mysql2:
        image: mysql:5.7
        container_name: mysql2
        environment:
             MYSQL_ROOT_PASSWORD: elmapadeobras
        networks:
            - mapasnet
        labels:
            - traefik.enable=false
