[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$SFb11QoI$Zm4avJgRVbHqfRZSu5Kza0"
  ]
[http.routers.api]
  rule = "Host(`monitor.proandtech.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
